### ISSUE TITLE
BUG: Clicking on the display name does not render the profile page of the author

### ISSUE THREAD

**Issue by setch-l** [planetary-social/viewer-frontend#102]
Steps to Reproduce:
1. Open planetary.link
2. Click on the author display name
Issue: Profile header flashes and page goes black

**Comment by nichoth** [comment]
Fixed in #104

**Comment by setch-l** [comment]
hi @nichoth - This seems to work for the main message, but for any reply I am not seeing this work consistently. I opened the javascript console while testing a click on AndreStaltz and saw a bunch of errors.
<img width="1540" alt="Screen Shot 2022-03-02 at 1 55 02 PM" src="https://user-images.githubusercontent.com/6765558/156429380-f2713c47-7fa6-4f29-b882-ed7b11ab372b.png">

**Comment by nichoth** [comment]
The errors about a CORS issue indicate that the server crashed (it restarts automatically). I have tried reproducing (clicking a reply avatar) and it seems ok at the moment.

**Comment by setch-l** [comment]
Hi @nichoth - Why do you think the server crashed? Do you think it's related to this change or to something completely different?

**Comment by nichoth** [comment]
Something random; it may be a memory leak somewhere deep in the ssb stack.
