### ISSUE TITLE
Hide likes from being displayed as individual messages in a user's feed page

### ISSUE THREAD

**Issue by rabble** [planetary-social/viewer-frontend#43]
When viewing a user's feed on planetary.link we should not see posts in their feed for the messages which are likes. For now, we can not display likes at all, or show the sum of likes on the message that was liked. We should not show them as a unique individual message in the user's feed. 

<img width="636" alt="Screen Shot 2022-02-03 at 2 37 04 PM" src="https://user-images.githubusercontent.com/76/152266929-8e72f59a-4d30-4ba4-8483-02cab68d753e.png">

**Comment by nichoth** [comment]
This depends on https://github.com/planetary-social/planetary-pub/issues/32

**Comment by nichoth** [comment]
The likes are still being returned by the DB, why?
