### ISSUE TITLE
urls for viewing a feed need to be the encoded identity not the name.

### ISSUE THREAD

**Issue by rabble** [planetary-social/viewer-frontend#44]
<img width="763" alt="Screen Shot 2022-02-03 at 4 14 47 PM" src="https://user-images.githubusercontent.com/76/152275720-0f594898-c7b9-4244-89e1-32796190ca4f.png">
Because multiple people can have the same username set in their about message, the web viewer needs to use a url safe encoding of their identity instead of the name. 

Being able to register a name, similar ot how rooms work, is super interesting, by beyond the scope of this initial release.

**Comment by nichoth** [comment]
* [ ] need a route on the pub side to handle fetching by user id
