### ISSUE TITLE
Profile set incorrectly when displaying a reply to a post in a user's feed

### ISSUE THREAD

**Issue by rabble** [planetary-social/viewer-frontend#48]
https://planetary.link/@0uOwBrHIeiRK7lcvpLwjSFkcS3UHSQb/jyN52zf+J6Y=.ed25519

It's showing the user who's url we're loading's profile instead of the original poster. 

And when other people who aren't me reply to a post, it doesn't show any identity all to say who  those comments are from

<img width="710" alt="Screen Shot 2022-02-08 at 8 01 29 PM" src="https://user-images.githubusercontent.com/76/152935162-358773b0-6154-4821-b8b6-03421d281100.png">

**Comment by nichoth** [comment]
> It's showing the user who's url we're loading's profile instead of the original poster.

* [ ] has correct profile on root post
