### ISSUE TITLE
fix url encoding on web app

### ISSUE THREAD

**Issue by setch-l** [planetary-social/viewer-frontend#63]
- fix a bug in the web viewer environment to enable it to accept the strings. 
- streamline encoding

Notes from Martin:
-> addingPercentEncoding(withAllowedCharacters:.rfc3986Unreserved)!
This is the encoding we do with the profile or message hash

**Comment by nichoth** [comment]
* [ ] don't replace `.` with `-dot-` in URLs

This is an error in the local dev environment. Need to yak shave the dev tools.

**Comment by nichoth** [comment]
Needed to update the command to start the server:

```
    "serve": "env $(cat .env | grep -v \"#\" | xargs) budo src/index.js:bundle.js --cors --pushstate [ --disallow \"\\.ed25519\" ] --dir=public --live --open -- -t envify -p esmify --debug",
```
