### ISSUE TITLE
CORS related problems

### ISSUE THREAD

**Issue by boreq** [planetary-social/viewer-frontend#88]
Sometimes the website fails to render and the following error is visible in the console.

![2022-02-22 13:33:16](https://user-images.githubusercontent.com/1935975/155140200-d24e6088-da69-4685-bde5-103699f8f57b.png)

This is the URL for which this error occurred for me.

https://planetary.link/msg/%25viaG5tkS%2ByX3IRPk8QH%2FZ1Ovg80sWNTvunCVBM60Lz4%3D.sha256

**Comment by nichoth** [comment]
This is because the server is crashing for some reason -- https://dashboard.render.com/

**Comment by boreq** [comment]
Let's close this for now then.
